/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.chatapp.view;

import com.chatapp.model.Account;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class ChangePasswordFrm extends javax.swing.JFrame {
    DataInputStream input;
    DataOutputStream output;
    Account account;
    String host = "localhost";
    private int port = 9999;
    private Socket socket;
    ChatFrm chatFrm;
    /**
     * Creates new form ChangePasswordFrm
     */
    public ChangePasswordFrm(ChatFrm chat,Account account, DataInputStream dis, DataOutputStream dos) {
        initComponents();
        chatFrm = chat;
        this.account = account;
        input = dis;
        output = dos;
        labelNotification.setVisible(false);
        
        txtCurrentPassword.setEchoChar('\u25cf');
        txtNewPassword.setEchoChar('\u25cf');
        txtConfirmPassword.setEchoChar('\u25cf');
        //this.lbHidePW.setVisible(false);       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelChangePass = new javax.swing.JLabel();
        txtCurrentPassword = new javax.swing.JPasswordField();
        labelCurrentPass = new javax.swing.JLabel();
        txtNewPassword = new javax.swing.JPasswordField();
        labelNewPass = new javax.swing.JLabel();
        txtConfirmPassword = new javax.swing.JPasswordField();
        labelConfirmPass = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnChange = new javax.swing.JButton();
        labelNotification = new javax.swing.JLabel();
        lbHidePW = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(255, 255, 153));
        jPanel1.setLayout(null);

        labelChangePass.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        labelChangePass.setText("Change Password");
        jPanel1.add(labelChangePass);
        labelChangePass.setBounds(220, 20, 300, 40);

        txtCurrentPassword.setBackground(new java.awt.Color(222, 222, 222));
        txtCurrentPassword.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        txtCurrentPassword.setForeground(new java.awt.Color(91, 90, 90));
        txtCurrentPassword.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtCurrentPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCurrentPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(txtCurrentPassword);
        txtCurrentPassword.setBounds(350, 80, 160, 34);

        labelCurrentPass.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        labelCurrentPass.setText("Current Password");
        jPanel1.add(labelCurrentPass);
        labelCurrentPass.setBounds(80, 90, 160, 23);

        txtNewPassword.setBackground(new java.awt.Color(222, 222, 222));
        txtNewPassword.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        txtNewPassword.setForeground(new java.awt.Color(91, 90, 90));
        txtNewPassword.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(txtNewPassword);
        txtNewPassword.setBounds(350, 130, 160, 34);

        labelNewPass.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        labelNewPass.setText("New Password");
        jPanel1.add(labelNewPass);
        labelNewPass.setBounds(80, 140, 160, 23);

        txtConfirmPassword.setBackground(new java.awt.Color(222, 222, 222));
        txtConfirmPassword.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        txtConfirmPassword.setForeground(new java.awt.Color(91, 90, 90));
        txtConfirmPassword.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(txtConfirmPassword);
        txtConfirmPassword.setBounds(350, 180, 160, 34);

        labelConfirmPass.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        labelConfirmPass.setText("Confirm Password");
        jPanel1.add(labelConfirmPass);
        labelConfirmPass.setBounds(80, 190, 180, 23);

        btnBack.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(51, 51, 51));
        btnBack.setText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack);
        btnBack.setBounds(140, 300, 90, 39);

        btnChange.setBackground(new java.awt.Color(30, 30, 30));
        btnChange.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        btnChange.setForeground(new java.awt.Color(255, 255, 255));
        btnChange.setText("Change");
        btnChange.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnChange.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });
        jPanel1.add(btnChange);
        btnChange.setBounds(300, 300, 100, 39);

        labelNotification.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        labelNotification.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(labelNotification);
        labelNotification.setBounds(220, 260, 340, 40);

        lbHidePW.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbHidePWMousePressed(evt);
            }
        });
        jPanel1.add(lbHidePW);
        lbHidePW.setBounds(450, 130, 40, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        chatFrm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        String notification = checkPassword();
        if(notification.equals("OK")==false) {
            labelNotification.setVisible(true);
            labelNotification.setText(notification);
        }
        else{
            try {
                connectToServer();
                output.writeUTF("Change Password");
                output.writeUTF(account.getUserName());
                output.writeUTF(txtCurrentPassword.getText());
                output.writeUTF(txtNewPassword.getText());
                String respon = input.readUTF();
                if(respon.equals("Current Password does not match")){
                    labelNotification.setVisible(true);
                    labelNotification.setText(respon);
                }
                else if(respon.equals("Not Update")){
                    labelNotification.setVisible(true);
                    labelNotification.setText("ERROR");
                }
                else{
                    JOptionPane.showMessageDialog(rootPane, "Update Successful");
                    account.setPassword(txtNewPassword.getText());
                    labelNotification.setText("");
                    labelNotification.setVisible(false);
                    txtConfirmPassword.setText("");
                    txtNewPassword.setText("");
                    txtCurrentPassword.setText("");
                    chatFrm.setPassword(account.getPassword());
                }
            } catch (IOException ex) {
                Logger.getLogger(ChangePasswordFrm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnChangeActionPerformed

    private void lbHidePWMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbHidePWMousePressed
        
    }//GEN-LAST:event_lbHidePWMousePressed

    private void txtCurrentPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCurrentPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCurrentPasswordActionPerformed
public void connectToServer() {
        try {
            if (socket != null) {
                socket.close();
            }
            socket = new Socket(host, port);
            this.input = new DataInputStream(socket.getInputStream());
            this.output = new DataOutputStream(socket.getOutputStream());
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }
    public String checkPassword(){
         if(txtCurrentPassword.getText().equals("") || txtNewPassword.getText().equals("") || txtConfirmPassword.getText().equals("")){
             return "Please enter full information";            
         }
         else if(txtNewPassword.getText().length()<8){
             return "Password must be at least 8 characters";
         }
         else if(txtNewPassword.getText().equals(txtConfirmPassword.getText())==false){
             return "Password does not match";
         }
         else return "OK";
        
    }
       
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnChange;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelChangePass;
    private javax.swing.JLabel labelConfirmPass;
    private javax.swing.JLabel labelCurrentPass;
    private javax.swing.JLabel labelNewPass;
    private javax.swing.JLabel labelNotification;
    private javax.swing.JLabel lbHidePW;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JPasswordField txtCurrentPassword;
    private javax.swing.JPasswordField txtNewPassword;
    // End of variables declaration//GEN-END:variables

   
}
